In [2]:
import numpy as np 

def load_dataset(filename):
    data_mat = []; label_mat = []
    with open(filename) as fr:
        for line in fr.readlines():
            line_arr = line.strip().split('\t')
            data_mat.append([float(line_arr[0]), float(line_arr[1])])
            label_mat.append(float(line_arr[2]))
    return data_mat, label_mat

def select_jrand(i, m):
    # 随机选择另一个优化的j,不等于i
    j = i 
    while j == i:
        j = np.random.randint(0, m)
    return j

def clip_alpha(aj, H, L):
    aj = max(aj, L)
    aj = min(aj, H)
    return aj

In [3]:
data_arr, label_arr = load_dataset('testSet.txt')
print(label_arr)

[-1.0, -1.0, 1.0, -1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, -1.0, -1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0, -1.0, -1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, 1.0, -1.0, 1.0, -1.0, -1.0, -1.0, -1.0, 1.0, -1.0, 1.0, -1.0, -1.0, 1.0, 1.0, 1.0, -1.0, 1.0, 1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, 1.0, -1.0, 1.0, 1.0, 1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0, -1.0]


In [10]:
def smo_simple(data, classlabels, C, toler, max_iter):
    """
    C:常数
    toler:容错率
    """
    data_mat = np.mat(data)
    label_mat = np.mat(classlabels).transpose()
    b = 0; m,n = np.shape(data_mat)
    alphas = np.mat(np.zeros((m, 1)))
    num = 0
    while (num < max_iter):
        alpha_pair_changed = 0 
        for i in range(m):
            fXi = float(np.multiply(alphas, label_mat).T * \
                (data_mat * data_mat[i, :].T)) + b  # 计算出的类别
            Ei = fXi - float(label_mat[i])  # 误差Ei，根据此优化
            if ((label_mat[i] * Ei < -toler) and (alphas[i] < C)) or \
                ((label_mat[i] * Ei > toler) and (alphas[i] > 0) and \
                    (alphas[i] > 0)):   # 如果alpha可以改更改进入优化过程
                j = select_jrand(i, m)  # 随机选择第二个alpha
                fXj = float(np.multiply(alphas, label_mat).T * \
                    (data_mat * data_mat[j, :].T)) + b 
                Ej = fXj - float(label_mat[j])
                alpha_i_old = alphas[i].copy()
                alpha_j_old = alphas[j].copy() # 
                if (label_mat[i] != label_mat[j]):
                    L = max(0, alphas[j] - alphas[i])
                    H = min(C, C + alphas[j] - alphas[i])
                else:
                    L = max(0, alphas[j] + alphas[i] - C)
                    H = min(C, alphas[j] + alphas[i])
                if L == H: 
                    # print("L==H")
                    continue
                eta = 2.0 * data_mat[i,:] * data_mat[i,:].T - \
                    data_mat[i,:]*data_mat[i,:].T - data_mat[j,:]*data_mat[j,:].T   # eta是alpha[j]的最优修改量
                if eta >=0: 
                    # print("eta>=0")
                    continue 
                alphas[j] -= label_mat[j]*(Ei - Ej)/eta
                alphas[j] = clip_alpha(alphas[j], H, L)
                if (abs(alphas[j] - alpha_j_old) < 0.00001):
                    # print("j not moving enough")
                    continue
                alphas[i] += label_mat[j] * label_mat[i] * (alpha_j_old - alphas[j])   # i的修改方向和j相反
                # 设置常数项
                b1 = b - Ei \
                    - label_mat[i] * (alphas[i] - alpha_i_old) * data_mat[i,:] * data_mat[i,:].T \
                    - label_mat[j] * (alphas[j] - alpha_j_old) * data_mat[i,:] * data_mat[j,:].T
                b2 = b - Ej \
                    - label_mat[i] * (alphas[i] - alpha_i_old) * data_mat[i,:] * data_mat[j,:].T \
                    - label_mat[j] * (alphas[j] - alpha_j_old) * data_mat[j,:] * data_mat[j,:].T
                if (0 < alphas[i]) and (C > alphas[i]):
                    b = b1 
                elif (0 < alphas[j]) and (C > alphas[j]):
                    b = b2 
                else:
                    b = (b1 + b2) / 2.0
                alpha_pair_changed += 1
                # print("iter : %d i:%d, pairs changed %d" % \
                #     (num, i, alpha_pair_changed))
        if (alpha_pair_changed == 0): 
            num += 1
        else: 
            num = 0
        # print("iteration number: %d" % num)
    return b, alphas

In [51]:
b, alphas = smo_simple(data_arr, label_arr, 0.6, 0.001, 40)

In [12]:
b

matrix([[-27.18501339]])

In [13]:
alphas[alphas>0]

matrix([[5.40900002e-01, 1.87916540e-02, 6.00000000e-01, 1.73381624e-01,
         3.03611838e-01, 5.54885114e-01, 1.73472348e-18]])

In [14]:
for i in range(100):
    if alphas[i] > 0.0:
        print(data_arr[i], label_arr[i])

[4.658191, 3.507396] -1.0
[8.197181, 1.545132] 1.0
[5.286862, -2.358286] 1.0
[6.016004, -3.753712] 1.0
[7.27946, -0.189572] 1.0
[-0.236713, -5.766721] -1.0
[9.803425, 1.495167] 1.0


In [15]:
# 利用完整的platt SMO 优化算法

In [45]:
class DataStruct:
    def __init__(self, data_mat, classlabels, C, toler):
        self.X = data_mat
        self.label_mat = classlabels
        self.C = C 
        self.tol = toler 
        self.m = np.shape(data_mat)[0]
        self.alphas = np.mat(np.zeros((self.m, 1)))
        self.b = 0
        self.e_cache = np.mat(np.zeros((self.m, 2)))


def calc_ek(ds, k):
    fXk = np.multiply(ds.alphas, ds.label_mat).T *\
        (ds.X * ds.X[k,:].T) + ds.b
    Ek = float(fXk[0][0]) - float(ds.label_mat[k])
    return Ek

def select_j(i, ds, Ei):
    max_k = -1
    max_deltaE = 0
    Ej = 0  # 内循环中的启发式方法
    ds.e_cache[i] = [1, Ei]
    valid_Ecache_lst = np.nonzero(np.array(ds.e_cache[:, 0]))[0]
    if (len(valid_Ecache_lst) > 1):
        # >1说明至之前计算过别的E，选择最大的进行优化
        for k in valid_Ecache_lst:
            if k == i:
                continue
            Ek = calc_ek(ds, k)
            deltaE = abs(Ei - Ek)
            if (deltaE > max_deltaE):
                max_k = k
                max_deltaE = deltaE 
        return max_k, Ej 
    else:
        # 第一次循环就直接随机选择一个j
        j = select_jrand(i, ds.m)
        Ej = calc_ek(ds, j)
    return j, Ej 


def updateEk(ds, k):
    Ek = calc_ek(ds, k)
    ds.e_cache[k] = [1, Ek]

In [55]:
def innerL(i, ds):
    Ei = calc_ek(ds, i)
    if ((ds.label_mat[i] * Ei < -ds.tol) and (ds.alphas[i] < ds.C)) or \
        ((ds.label_mat[i] * Ei > ds.tol) and (ds.alphas[i] > 0)):
        j, Ej = select_j(i, ds, Ei) # 第二个alpha选择中的启发式方法
        alpha_i_old = ds.alphas[i].copy()
        alpha_j_old = ds.alphas[j].copy()
        if (ds.label_mat[i] != ds.label_mat[j]):
            L = max(0, ds.label_mat[j] - ds.label_mat[i])
            H = min(ds.C, ds.C + ds.label_mat[j] - ds.label_mat[i])
        else:
            L = max(0, ds.label_mat[j] + ds.label_mat[i] - ds.C)
            H = min(ds.C, ds.label_mat[j] + ds.label_mat[i])
        if L == H:
            # print("L==H")
            return 0 
        eta = 2.0 * ds.X[i,:] * ds.X[i,:].T - \
                    ds.X[i,:]*ds.X[i,:].T - ds.X[j,:]*ds.X[j,:].T
        if eta >=0: 
            # print("eta>=0")
            return 0 
        ds.alphas[j] -= ds.label_mat[j]*(Ei - Ej)/eta
        ds.alphas[j] = clip_alpha(ds.alphas[j], H, L)
        updateEk(ds, j)
        if (abs(alphas[j] - alpha_j_old) < 0.00001):
            # print("j not moving enough")
            return 0
        ds.alphas[i] += ds.label_mat[j] * ds.label_mat[i] * (alpha_j_old - ds.alphas[j])
        updateEk(ds, i) # 更新误差缓存
        b1 = ds.b - Ei \
            - ds.label_mat[i] * (ds.alphas[i] - alpha_i_old) * ds.X[i,:] * ds.X[i,:].T \
            - ds.label_mat[j] * (ds.alphas[j] - alpha_j_old) * ds.X[i,:] * ds.X[j,:].T
        b2 = ds.b - Ej \
            - ds.label_mat[i] * (ds.alphas[i] - alpha_i_old) * ds.X[i,:] * ds.X[j,:].T \
            - ds.label_mat[j] * (ds.alphas[j] - alpha_j_old) * ds.X[j,:] * ds.X[j,:].T
        if (0 < ds.alphas[i]) and (ds.C > ds.alphas[i]):
            ds.b = b1 
        elif (0 < ds.alphas[j]) and (ds.C > ds.alphas[j]):
            ds.b = b2 
        else:
            ds.b = (b1 + b2) / 2.0
        return 1 
    else:
        return 0

In [62]:
def smo_p(data_mat, classlabels, C, toler, max_iter, kTup=('lin', 0)):
    """完整SMO算法中的外循环代码"""
    ds = DataStruct(np.mat(data_mat), np.mat(classlabels).transpose(), C, toler)
    num = 0
    entire_set = True 
    alpha_pairs_changed = 0
    while (num < max_iter) and ((alpha_pairs_changed > 0) or (entire_set)):
        alpha_pairs_changed = 0
        if entire_set:  # 遍历所有值
            for i in range(ds.m):
                alpha_pairs_changed += innerL(i, ds)
            # print("Fullset, iter: %d i: %d, pairs changed %d" %\
            #     (num, i, alpha_pairs_changed))
            num += 1
        else:       # 遍历非边界值
            non_bounds = np.nonzero((np.array(ds.alphas) > 0) * (np.array(ds.alphas) < C))[0]
            for i in non_bounds:
                alpha_pairs_changed += innerL(i, ds)
                # print("non-bound, iter: %d i: %d, pairs changed %d" %\
                #     (num, i, alpha_pairs_changed))
                num += 1
        if entire_set:
            entire_set = False 
        elif alpha_pairs_changed == 0:
            entire_set = True 
        # print("iteration number: %d" % num)
    return ds.b, ds.alphas

In [75]:
data_arr, label_arr = load_dataset('testSet.txt')
b, alphas = smo_p(data_arr, label_arr, 0.6, 0.001, 40)

In [76]:
b

matrix([[-17.01456721]])

In [77]:
alphas[alphas>0.0]

matrix([[0.6, 0.6]])

In [78]:
for i in range(100):
    if alphas[i] > 0.0:
        print(data_arr[i], label_arr[i])

[7.55151, -1.58003] 1.0
[2.114999, -0.004466] -1.0


In [79]:
def calc_ws(alphas, data_arr, classlabels):
    X = np.mat(data_arr)
    label_mat = np.mat(classlabels).transpose()
    m,n = np.shape(X)
    w = np.zeros((n,1))
    for i in range(m):
        w += np.multiply(alphas[i] * label_mat[i], X[i,:].T)
    return w

In [80]:
ws = calc_ws(alphas, data_arr, label_arr)

In [81]:
ws

array([[ 3.2619066],
       [-0.9453384]])

In [82]:
label_arr[0]

-1.0

In [86]:
data_arr[1] * np.mat(ws) + b

matrix([[-9.58388863]])

In [87]:
label_arr[1]

-1.0

核函数

In [93]:
def kernel_trans(X, A, ktup):
    m,n = np.shape(X)
    K = np.mat(np.zeros(m, 1))
    if ktup[0] == 'lin':
        K = X * A.T 
    elif ktup[0] == 'rbf':
        for j in range(m):
            delta_row = X[j, :] - A 
            K[j] = delta_row * delta_row.T 
        K = np.exp(K / (-1*ktup[1]**2)) # 元素间的除法
    else:
        raise NameError('Houston We Have a Problem --\
            That Kernel is not recognized')
    return K

In [94]:
class DataStruct:
    def __init__(self, data_mat, classlabels, C, toler, ktup):
        self.X = data_mat
        self.label_mat = classlabels
        self.C = C 
        self.tol = toler 
        self.m = np.shape(data_mat)[0]
        self.alphas = np.mat(np.zeros((self.m, 1)))
        self.b = 0
        self.e_cache = np.mat(np.zeros((self.m, 2)))
        self.K = np.mat(np.zeros(self.m, self.m))
        for i in range(self.m):
            self.K[:,i] = kernel_trans(self.X, self.X[i,:], ktup)

In [95]:
def innerL(i, ds):
    Ei = calc_ek(ds, i)
    if ((ds.label_mat[i] * Ei < -ds.tol) and (ds.alphas[i] < ds.C)) or \
        ((ds.label_mat[i] * Ei > ds.tol) and (ds.alphas[i] > 0)):
        j, Ej = select_j(i, ds, Ei) # 第二个alpha选择中的启发式方法
        alpha_i_old = ds.alphas[i].copy()
        alpha_j_old = ds.alphas[j].copy()
        if (ds.label_mat[i] != ds.label_mat[j]):
            L = max(0, ds.label_mat[j] - ds.label_mat[i])
            H = min(ds.C, ds.C + ds.label_mat[j] - ds.label_mat[i])
        else:
            L = max(0, ds.label_mat[j] + ds.label_mat[i] - ds.C)
            H = min(ds.C, ds.label_mat[j] + ds.label_mat[i])
        if L == H:
            # print("L==H")
            return 0 
        eta = 2.0 * ds.K[i,j] - ds.K[i,i] - ds.K[j,j]
        if eta >=0: 
            # print("eta>=0")
            return 0 
        ds.alphas[j] -= ds.label_mat[j]*(Ei - Ej)/eta
        ds.alphas[j] = clip_alpha(ds.alphas[j], H, L)
        updateEk(ds, j)
        if (abs(alphas[j] - alpha_j_old) < 0.00001):
            # print("j not moving enough")
            return 0
        ds.alphas[i] += ds.label_mat[j] * ds.label_mat[i] * (alpha_j_old - ds.alphas[j])
        updateEk(ds, i) # 更新误差缓存
        b1 = ds.b - Ei \
            - ds.label_mat[i] * (ds.alphas[i] - alpha_i_old) * ds.K[i,i] \
            - ds.label_mat[j] * (ds.alphas[j] - alpha_j_old) * ds.K[i,j]
        b2 = ds.b - Ej \
            - ds.label_mat[i] * (ds.alphas[i] - alpha_i_old) * ds.K[i,j] \
            - ds.label_mat[j] * (ds.alphas[j] - alpha_j_old) * ds.K[j,j]
        if (0 < ds.alphas[i]) and (ds.C > ds.alphas[i]):
            ds.b = b1 
        elif (0 < ds.alphas[j]) and (ds.C > ds.alphas[j]):
            ds.b = b2 
        else:
            ds.b = (b1 + b2) / 2.0
        return 1 
    else:
        return 0


def calc_ek(ds, k):
    fXk = np.multiply(ds.alphas, ds.label_mat).T *\
        ds.K[:,k] + ds.b
    Ek = float(fXk[0][0]) - float(ds.label_mat[k])
    return Ek

In [ ]:
# 利用核函数进行分类的径向基测试函数

def test_rbf(k1 = 1.3):
    